### ISSUE TITLE
jquery.js:1496 Uncaught Error: Syntax error, unrecognized expression: input#

### ISSUE THREAD

**Issue by lunarstack1** [mlutfy/ca.bidon.civiexportexcel#4]
The Export to Excel button doesn't work on a Drupal site (latest Drupal 7) and CiviCRM 4.7.7
Have toggled JS aggregation and using another version of jQuery. Thus the button doesn't execute to generate the excel file.

**Comment by urlisse** [comment]
I was able to reproduce this bug on a CiviCRM 4.7.12 instance. 

It would appear that the {$form.$csv.id} token is substituted to nothing, therefore calling jQuery with an empty ID. Actually, it looks like there are no elements named _qf_FORMNAME_submit_csv on the page...

In any case, the Export to Excel button has no effect at all.

**Comment by francescbassas** [comment]
Same here with 4.7.12.

**Comment by mlutfy** [comment]
The fix is not ideal, but I patched the code so that it doesn't cause any problems in 4.7.

Ideally, we would add "export to Excel" as a task, but that may require adding hooks in Core.
